# Generated by Django 4.0.3 on 2022-06-21 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atributos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome')),
                ('forca', models.IntegerField(blank=True, null=True, verbose_name='Força')),
                ('agilidade', models.IntegerField(blank=True, null=True, verbose_name='Agilidade')),
                ('inteligencia', models.IntegerField(blank=True, null=True, verbose_name='Inteligência')),
                ('vigor', models.IntegerField(blank=True, null=True, verbose_name='Vigor')),
                ('presenca', models.IntegerField(blank=True, null=True, verbose_name='Presença')),
            ],
        ),
        migrations.CreateModel(
            name='Pericias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome')),
                ('origem', models.CharField(blank=True, max_length=50, null=True, verbose_name='Origem')),
                ('nex', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nível de Exposição Paranormal')),
                ('patente', models.CharField(blank=True, max_length=50, null=True, verbose_name='Patente')),
                ('classe', models.CharField(blank=True, max_length=30, null=True, verbose_name='Classe')),
            ],
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('atributos', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='game.atributos', verbose_name='Atributos')),
                ('jogador', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='jogador', to=settings.AUTH_USER_MODEL, verbose_name='Jogador')),
                ('mestre', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mestre', to=settings.AUTH_USER_MODEL, verbose_name='Mestre')),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='game.personagem', verbose_name='Informações Gerais')),
            ],
        ),
    ]
