# Generated by Django 4.0.3 on 2022-06-21 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Atributos',
            new_name='Atributo',
        ),
        migrations.RenameModel(
            old_name='Personagem',
            new_name='Personagen',
        ),
    ]
