# Generated by Django 4.0.3 on 2022-06-21 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0003_alter_atributo_id_alter_ficha_id_alter_personagen_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='jogador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='jogador', to=settings.AUTH_USER_MODEL, verbose_name='Jogador'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='mestre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mestre', to=settings.AUTH_USER_MODEL, verbose_name='Mestre'),
        ),
    ]
