# Generated by Django 4.0.3 on 2022-06-21 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_ficha_jogador_alter_ficha_mestre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atributo',
            name='nome',
        ),
    ]
